INSERT INTO WEBCONTIFY_COLLECTION VALUES(1,'name','DisplayName');
INSERT INTO WEBCONTIFY_COLLECTION_FIELD VALUES(1,1,'name','DisplayName','NUMBER',true);
INSERT INTO WEBCONTIFY_COLLECTION_FIELD VALUES(2,1,'name_2','DisplayName','NUMBER',true);