INSERT INTO WEBCONTIFY_COLLECTION VALUES(1,'test','DisplayName');
INSERT INTO WEBCONTIFY_COLLECTION_FIELD VALUES(1,1,'id','DisplayName','NUMBER',true);
INSERT INTO WEBCONTIFY_COLLECTION_FIELD VALUES(2,1,'other_field','DisplayName','NUMBER',true);
CREATE TABLE TEST (id bigint, OTHER_FIELD bigint, constraint PK_test primary key (id));
INSERT INTO TEST VALUES(1,1);
INSERT INTO TEST VALUES(2,2);