DELETE FROM WEBCONTIFY_COLLECTION_RELATION_FIELD;
DELETE FROM WEBCONTIFY_COLLECTION_RELATION;
DELETE FROM WEBCONTIFY_COLLECTION_COLUMN;
DELETE FROM WEBCONTIFY_COLLECTION;

DROP TABLE IF EXISTS ALL_COLUMN_TYPES_PRIMARY_NUMBER;
DROP TABLE IF EXISTS ALL_COLUMN_TYPES_PRIMARY_UUID;
DROP TABLE IF EXISTS TEST;