INSERT INTO WEBCONTIFY_COLLECTION VALUES(1,'name','DisplayName');
INSERT INTO WEBCONTIFY_COLLECTION_COLUMN VALUES(1,'name','DisplayName','NUMBER',true);
INSERT INTO WEBCONTIFY_COLLECTION_COLUMN VALUES(1,'name2','DisplayName','NUMBER',true);