INSERT INTO "WEBCONTIFY_COLLECTION" VALUES(1,'Name','DisplayName');
INSERT INTO "WEBCONTIFY_COLLECTION_COLUMN" VALUES(1,'Name','DisplayName','NUMBER',true);
INSERT INTO "WEBCONTIFY_COLLECTION_COLUMN" VALUES(1,'Name2','DisplayName','NUMBER',true);