INSERT INTO WEBCONTIFY_COLLECTION VALUES(1,'test','DisplayName');
INSERT INTO WEBCONTIFY_COLLECTION_COLUMN VALUES(1,'id','DisplayName','NUMBER',true);
INSERT INTO WEBCONTIFY_COLLECTION_COLUMN VALUES(1,'other_column','DisplayName','NUMBER',true);
create table TEST (id bigint generated by default as identity, OTHER_COLUMN bigint, constraint PK_TEST primary key (id));