INSERT INTO WEBCONTIFY_COLLECTION VALUES(1,'test','DisplayName');
INSERT INTO WEBCONTIFY_COLLECTION_FIELD VALUES(1,1,'id','DisplayName','NUMBER',true);
INSERT INTO WEBCONTIFY_COLLECTION_FIELD VALUES(2,1,'other_field','DisplayName','NUMBER',true);
create table TEST (id bigint generated by default as identity, OTHER_FIELD bigint, constraint PK_TEST primary key (id));