INSERT INTO WEBCONTIFY_COLLECTION VALUES(1,'test','DisplayName');
INSERT INTO WEBCONTIFY_COLLECTION_COLUMN VALUES(1,'id','DisplayName','NUMBER',true);
INSERT INTO WEBCONTIFY_COLLECTION_COLUMN VALUES(1,'other_column','DisplayName','NUMBER',true);
CREATE TABLE TEST (id bigint, OTHER_COLUMN bigint, constraint PK_test primary key (id));
INSERT INTO TEST VALUES(1,1);
INSERT INTO TEST VALUES(2,2);