INSERT INTO "WEBCONTIFY_COLLECTION" VALUES(1,'TEST','DisplayName');
INSERT INTO "WEBCONTIFY_COLLECTION_COLUMN" VALUES(1,'PRIMARY','DisplayName','NUMBER',true);
INSERT INTO "WEBCONTIFY_COLLECTION_COLUMN" VALUES(1,'OTHER_COLUMN','DisplayName','NUMBER',true);
CREATE TABLE "TEST" ("PRIMARY" bigint, "OTHER_COLUMN" bigint, constraint "PK_test" primary key ("PRIMARY"));
INSERT INTO "TEST" VALUES(1,1);
INSERT INTO "TEST" VALUES(2,2)