INSERT INTO WEBCONTIFY_COLLECTION(ID,NAME,DISPLAY_NAME) VALUES(1,'related_collection','RelatedCollection');
INSERT INTO WEBCONTIFY_COLLECTION_FIELD(ID,COLLECTION_ID,NAME,DISPLAY_NAME,TYPE,IS_PRIMARY_KEY) VALUES(1,1,'number_field','Primary Field','NUMBER',true);

CREATE TABLE IF NOT EXISTS RELATED_COLLECTION (
    number_field bigint GENERATED ALWAYS AS IDENTITY,
    constraint PK_RELATED_COLLECTION_NUMBER primary key (number_field)
);
CREATE TABLE IF NOT EXISTS COLLECTION_WITH_RELATION (
    number_field bigint GENERATED ALWAYS AS IDENTITY,
    related_field bigint,
    constraint PK_COLLECTION_WITH_RELATION_NUMBER primary key (number_field),
    FOREIGN KEY(related_field) references RELATED_COLLECTION(number_field)
);
INSERT INTO WEBCONTIFY_COLLECTION(ID,NAME,DISPLAY_NAME) VALUES(2,'collection_with_relation','CollectionWithRelation');
INSERT INTO WEBCONTIFY_COLLECTION_FIELD(ID,COLLECTION_ID,NAME,DISPLAY_NAME,TYPE,IS_PRIMARY_KEY) VALUES(2,2,'number_field','Primary Field','NUMBER',true);
INSERT INTO WEBCONTIFY_COLLECTION_FIELD(ID,COLLECTION_ID,NAME,DISPLAY_NAME,TYPE,IS_PRIMARY_KEY) VALUES(3,2,'related_field','Related Field','NUMBER',false);

INSERT INTO WEBCONTIFY_COLLECTION_RELATION (ID,SOURCE_COLLECTION_ID, REFERENCED_COLLECTION_ID, TYPE) VALUES (1,2,1, 'MANY_TO_ONE');
INSERT INTO WEBCONTIFY_COLLECTION_RELATION_FIELD(relation_id, SOURCE_FIELD_ID, REFERENCED_FIELD_ID) VALUES (1, 3, 1);

INSERT INTO WEBCONTIFY_COLLECTION_RELATION (ID,SOURCE_COLLECTION_ID, REFERENCED_COLLECTION_ID, TYPE) VALUES (2,1,2, 'ONE_TO_MANY');
INSERT INTO WEBCONTIFY_COLLECTION_RELATION_FIELD(relation_id, SOURCE_FIELD_ID, REFERENCED_FIELD_ID) VALUES (2, 1,3);
