DELETE FROM WEBCONTIFY_QUERY_RELATION;
DELETE FROM WEBCONTIFY_QUERY;
DELETE FROM WEBCONTIFY_COLLECTION_RELATION_FIELD;
DELETE FROM WEBCONTIFY_COLLECTION_RELATION;
DELETE FROM WEBCONTIFY_COLLECTION_FIELD;
DELETE FROM WEBCONTIFY_COLLECTION;

DROP TABLE IF EXISTS ALL_FIELD_TYPES_PRIMARY_NUMBER;
DROP TABLE IF EXISTS ALL_FIELD_TYPES_PRIMARY_UUID;
DROP TABLE IF EXISTS COLLECTION_WITH_RELATION;
DROP TABLE IF EXISTS RELATED_COLLECTION;
DROP TABLE IF EXISTS TEST;