package io.webcontify.backend.collections.services.field.handler.strategies

import io.webcontify.backend.collections.models.dtos.*
import io.webcontify.backend.collections.services.field.handler.FieldHandler
import io.webcontify.backend.collections.utils.addGreaterThanIfPresent
import io.webcontify.backend.collections.utils.addLessThanIfPresent
import io.webcontify.backend.jooq.enums.WebcontifyCollectionFieldType
import java.math.BigDecimal
import org.jooq.ConstraintEnforcementStep
import org.jooq.DataType
import org.jooq.JSONB
import org.jooq.impl.SQLDataType
import org.jooq.jackson.extensions.converters.JSONBtoJacksonConverter
import org.springframework.stereotype.Service

@Service
class DecimalFieldHandler : FieldHandler<BigDecimal> {

  private val converter =
      JSONBtoJacksonConverter(WebContifyCollectionFieldDecimalConfigurationDto::class.java)

  override fun mapJSONBToConfiguration(
      configuration: JSONB?
  ): WebContifyCollectionFieldDecimalConfigurationDto? {
    return converter.from(configuration)
  }

  override fun getFieldType(
      field: WebContifyCollectionFieldDto,
      isAutogenerated: Boolean
  ): DataType<BigDecimal> {
    var type = super.getFieldType(field, isAutogenerated)
    field.configuration?.let {
      it as WebContifyCollectionFieldDecimalConfigurationDto
      if (it.precision != null) {
        type = type.precision(it.precision)
      }
      if (it.scale != null) {
        type = type.scale(it.scale)
      }
    }
    return type
  }

  override fun getFieldType(): DataType<BigDecimal> {
    return SQLDataType.DECIMAL
  }

  override fun getFieldHandlerType(): WebcontifyCollectionFieldType {
    return WebcontifyCollectionFieldType.DECIMAL
  }

  override fun getFieldConstraints(
      field: WebContifyCollectionFieldDto,
      tableName: String
  ): List<ConstraintEnforcementStep> {
    val list = super.getFieldConstraints(field, tableName).toMutableList()
    field.configuration?.let {
      if (WebContifyCollectionFieldDecimalConfigurationDto::class.isInstance(it)) {
        it as WebContifyCollectionFieldDecimalConfigurationDto
        list.addGreaterThanIfPresent(tableName, field.name, it.greaterThan, it.greaterThan)
        list.addLessThanIfPresent(tableName, field.name, it.lowerThan, it.lowerThan)
      }
    }
    return list.toList()
  }

  override fun castToJavaType(value: Any?): BigDecimal? {
    if (value is Double) {
      return value.toBigDecimal()
    }
    if (value is String) {
      try {
        return value.toBigDecimal()
      } catch (exception: NumberFormatException) {
        throw CastException()
      }
    }
    throw CastException()
  }

  override fun validateField(
      value: BigDecimal?,
      configuration: WebContifyCollectionFieldConfigurationDto<Any>?
  ) {
    super.validateField(value, configuration)
    configuration?.let {
      it as WebContifyCollectionFieldDecimalConfigurationDto
      if (value == null) {
        return
      }
      if (it.greaterThan != null && value <= it.greaterThan) {
        throw ValidationException()
      }
      if (it.lowerThan != null && value >= it.lowerThan) {
        throw ValidationException()
      }
    }
  }
}
