package io.webcontify.backend.collections.services.field.handler.strategies

import io.webcontify.backend.collections.models.dtos.CastException
import io.webcontify.backend.collections.models.dtos.WebContifyCollectionFieldDto
import io.webcontify.backend.collections.models.dtos.WebContifyCollectionFieldUuidConfigurationDto
import io.webcontify.backend.collections.services.field.handler.FieldHandler
import io.webcontify.backend.collections.services.field.handler.UUID_FIELD_TYPE
import java.util.*
import org.jooq.DataType
import org.jooq.JSONB
import org.jooq.impl.DSL
import org.jooq.impl.SQLDataType
import org.jooq.jackson.extensions.converters.JSONBtoJacksonConverter
import org.springframework.stereotype.Component

@Component(UUID_FIELD_TYPE)
class UuidFieldHandler : FieldHandler<UUID> {

  private val converter =
      JSONBtoJacksonConverter(WebContifyCollectionFieldUuidConfigurationDto::class.java)

  override fun getFieldType(): DataType<UUID> {
    return SQLDataType.UUID
  }

  override fun getFieldType(
      field: WebContifyCollectionFieldDto,
      isAutogenerated: Boolean
  ): DataType<UUID> {
    var type = super.getFieldType(field, isAutogenerated)!!
    if (field.isPrimaryKey && isAutogenerated) {
      type = type.defaultValue(DSL.uuid())
    }
    return type
  }

  override fun castToJavaType(value: Any?): UUID? {
    if (value == null) {
      return null
    }
    if (value is UUID) {
      return value
    }
    if (value is String) {
      try {
        return UUID.fromString(value)
      } catch (exception: IllegalArgumentException) {
        throw CastException()
      }
    }
    throw CastException()
  }

  override fun mapJSONBToConfiguration(
      configuration: JSONB?
  ): WebContifyCollectionFieldUuidConfigurationDto? {
    return converter.from(configuration)
  }
}
