drop table if exists WEBCONTIFY_COLLECTION_RELATION CASCADE;
drop type if exists WEBCONTIFY_RELATION_TYPE CASCADE;
drop table if exists WEBCONTIFY_COLLECTION CASCADE;
drop table if exists WEBCONTIFY_COLLECTION_COLUMN CASCADE;
drop type if exists WEBCONTIFY_COLLECTION_COLUMN_TYPE CASCADE;

create table WEBCONTIFY_COLLECTION(
    ID SERIAL PRIMARY KEY,
    NAME TEXT UNIQUE NOT NULL,
    DISPLAY_NAME TEXT NOT NULL
);

create type WEBCONTIFY_COLLECTION_COLUMN_TYPE as enum (
    'NUMBER',
    'DECIMAL',
    'TEXT',
    'TIMESTAMP',
    'BOOLEAN',
    'UUID'
);

create table WEBCONTIFY_COLLECTION_COLUMN(
    COLLECTION_ID INT REFERENCES WEBCONTIFY_COLLECTION(ID),
    NAME TEXT NOT NULL,
    DISPLAY_NAME TEXT NOT NULL,
    TYPE WEBCONTIFY_COLLECTION_COLUMN_TYPE NOT NULL,
    IS_PRIMARY_KEY BOOLEAN NOT NULL,
    CONFIGURATION JSONB,
    PRIMARY KEY (COLLECTION_ID, NAME)
);

create type WEBCONTIFY_COLLECTION_RELATION_TYPE as enum (
    'ONE_TO_ONE',
    'ONE_TO_MANY',
    'MANY_TO_MANY',
    'MANY_TO_ONE'
);

create table WEBCONTIFY_COLLECTION_RELATION(
    SOURCE_COLLECTION_ID INT NOT NULL,
    SOURCE_COLLECTION_COLUMN_NAME TEXT NOT NULL,
    REFERENCED_COLLECTION_ID INT NOT NULL,
    REFERENCED_COLLECTION_COLUMN_NAME TEXT NOT NULL,
    TYPE WEBCONTIFY_COLLECTION_RELATION_TYPE NOT NULL,
    NAME TEXT NOT NULL,
    DISPLAY_NAME TEXT NOT NULL,
    PRIMARY KEY (SOURCE_COLLECTION_ID,SOURCE_COLLECTION_COLUMN_NAME,REFERENCED_COLLECTION_ID,REFERENCED_COLLECTION_COLUMN_NAME,NAME,TYPE),
    FOREIGN KEY (SOURCE_COLLECTION_ID,SOURCE_COLLECTION_COLUMN_NAME) REFERENCES WEBCONTIFY_COLLECTION_COLUMN(COLLECTION_ID,NAME),
    FOREIGN KEY (REFERENCED_COLLECTION_ID,REFERENCED_COLLECTION_COLUMN_NAME) REFERENCES WEBCONTIFY_COLLECTION_COLUMN(COLLECTION_ID,NAME),
    FOREIGN KEY (SOURCE_COLLECTION_ID) REFERENCES WEBCONTIFY_COLLECTION(ID),
    FOREIGN KEY (REFERENCED_COLLECTION_ID) REFERENCES WEBCONTIFY_COLLECTION(ID)
);
