INSERT INTO WEBCONTIFY_COLLECTION(ID,NAME,DISPLAY_NAME) VALUES(1,'related_collection','RelatedCollection');
INSERT INTO WEBCONTIFY_COLLECTION_COLUMN(ID,COLLECTION_ID,NAME,DISPLAY_NAME,TYPE,IS_PRIMARY_KEY) VALUES(1,1,'number_column','Primary Column','NUMBER',true);

CREATE TABLE IF NOT EXISTS RELATED_COLLECTION (
    number_column bigint GENERATED ALWAYS AS IDENTITY,
    constraint PK_RELATED_COLLECTION_NUMBER primary key (number_column)
);
CREATE TABLE IF NOT EXISTS COLLECTION_WITH_RELATION (
    number_column bigint GENERATED ALWAYS AS IDENTITY,
    related_column bigint,
    constraint PK_COLLECTION_WITH_RELATION_NUMBER primary key (number_column),
    FOREIGN KEY(related_column) references RELATED_COLLECTION(number_column)
);
INSERT INTO WEBCONTIFY_COLLECTION(ID,NAME,DISPLAY_NAME) VALUES(2,'collection_with_relation','CollectionWithRelation');
INSERT INTO WEBCONTIFY_COLLECTION_COLUMN(ID,COLLECTION_ID,NAME,DISPLAY_NAME,TYPE,IS_PRIMARY_KEY) VALUES(2,2,'number_column','Primary Column','NUMBER',true);
INSERT INTO WEBCONTIFY_COLLECTION_COLUMN(ID,COLLECTION_ID,NAME,DISPLAY_NAME,TYPE,IS_PRIMARY_KEY) VALUES(3,2,'related_column','Related Column','NUMBER',false);

INSERT INTO WEBCONTIFY_COLLECTION_RELATION (ID,SOURCE_COLLECTION_ID, REFERENCED_COLLECTION_ID, TYPE,NAME,DISPLAY_NAME) VALUES (1,2,1, 'MANY_TO_ONE', 'relation', 'Relation');
INSERT INTO WEBCONTIFY_COLLECTION_RELATION_COLLECTION_FIELD(relation_id, SOURCE_COLUMN_ID, REFERENCED_COLUMN_ID) VALUES (1, 3, 1);

INSERT INTO WEBCONTIFY_COLLECTION_RELATION (ID,SOURCE_COLLECTION_ID, REFERENCED_COLLECTION_ID, TYPE,NAME,DISPLAY_NAME) VALUES (2,1,2, 'ONE_TO_MANY', 'relation', 'Relation');
INSERT INTO WEBCONTIFY_COLLECTION_RELATION_COLLECTION_FIELD(relation_id, SOURCE_COLUMN_ID, REFERENCED_COLUMN_ID) VALUES (2, 1,3);