INSERT INTO WEBCONTIFY_COLLECTION(NAME,DISPLAY_NAME) VALUES('related_collection','RelatedCollection');
INSERT INTO WEBCONTIFY_COLLECTION_COLUMN(COLLECTION_ID,NAME,DISPLAY_NAME,TYPE,IS_PRIMARY_KEY) VALUES((SELECT ID FROM WEBCONTIFY_COLLECTION WHERE name = 'related_collection'),'number_column','Primary Column','NUMBER',true);

CREATE TABLE IF NOT EXISTS RELATED_COLLECTION (
    number_column bigint GENERATED ALWAYS AS IDENTITY,
    constraint PK_RELATED_COLLECTION_NUMBER primary key (number_column)
);
CREATE TABLE IF NOT EXISTS COLLECTION_WITH_RELATION (
    number_column bigint GENERATED ALWAYS AS IDENTITY,
    related_column bigint,
    constraint PK_COLLECTION_WITH_RELATION_NUMBER primary key (number_column),
    FOREIGN KEY(related_column) references RELATED_COLLECTION(number_column)
);
INSERT INTO WEBCONTIFY_COLLECTION(NAME,DISPLAY_NAME) VALUES('collection_with_relation','CollectionWithRelation');
INSERT INTO WEBCONTIFY_COLLECTION_COLUMN(COLLECTION_ID,NAME,DISPLAY_NAME,TYPE,IS_PRIMARY_KEY) VALUES((SELECT ID FROM WEBCONTIFY_COLLECTION WHERE name = 'collection_with_relation'),'number_column','Primary Column','NUMBER',true);
INSERT INTO WEBCONTIFY_COLLECTION_COLUMN(COLLECTION_ID,NAME,DISPLAY_NAME,TYPE,IS_PRIMARY_KEY) VALUES((SELECT ID FROM WEBCONTIFY_COLLECTION WHERE name = 'collection_with_relation'),'related_column','Related Column','NUMBER',false);

INSERT INTO WEBCONTIFY_COLLECTION_RELATION (SOURCE_COLLECTION_ID, REFERENCED_COLLECTION_ID, TYPE,NAME,DISPLAY_NAME) VALUES ((SELECT ID FROM WEBCONTIFY_COLLECTION WHERE name = 'collection_with_relation'),(SELECT ID FROM WEBCONTIFY_COLLECTION WHERE name = 'related_collection'), 'MANY_TO_ONE', 'relation', 'Relation');
INSERT INTO WEBCONTIFY_COLLECTION_RELATION_COLLECTION_FIELD(relation_id, SOURCE_COLUMN_ID, REFERENCED_COLUMN_ID) VALUES ((SELECT ID FROM WEBCONTIFY_COLLECTION_RELATION where SOURCE_COLLECTION_ID = (SELECT ID FROM WEBCONTIFY_COLLECTION WHERE name = 'collection_with_relation') and REFERENCED_COLLECTION_ID = (SELECT ID FROM WEBCONTIFY_COLLECTION WHERE name = 'related_collection')), (SELECT ID FROM WEBCONTIFY_COLLECTION_COLUMN where COLLECTION_ID = (SELECT ID FROM WEBCONTIFY_COLLECTION WHERE name = 'collection_with_relation') and NAME = 'related_column'), (SELECT ID FROM WEBCONTIFY_COLLECTION_COLUMN where COLLECTION_ID = (SELECT ID FROM WEBCONTIFY_COLLECTION WHERE name = 'related_collection') and NAME = 'number_column'));

INSERT INTO WEBCONTIFY_COLLECTION_RELATION (SOURCE_COLLECTION_ID, REFERENCED_COLLECTION_ID, TYPE,NAME,DISPLAY_NAME) VALUES ((SELECT ID FROM WEBCONTIFY_COLLECTION WHERE name = 'related_collection'),(SELECT ID FROM WEBCONTIFY_COLLECTION WHERE name = 'collection_with_relation'), 'ONE_TO_MANY', 'relation', 'Relation');
INSERT INTO WEBCONTIFY_COLLECTION_RELATION_COLLECTION_FIELD(relation_id, SOURCE_COLUMN_ID, REFERENCED_COLUMN_ID) VALUES ((SELECT ID FROM WEBCONTIFY_COLLECTION_RELATION where SOURCE_COLLECTION_ID = (SELECT ID FROM WEBCONTIFY_COLLECTION WHERE name = 'related_collection') and REFERENCED_COLLECTION_ID = (SELECT ID FROM WEBCONTIFY_COLLECTION WHERE name = 'collection_with_relation')), (SELECT ID FROM WEBCONTIFY_COLLECTION_COLUMN where COLLECTION_ID = (SELECT ID FROM WEBCONTIFY_COLLECTION WHERE name = 'related_collection') and NAME = 'number_column'),(SELECT ID FROM WEBCONTIFY_COLLECTION_COLUMN where COLLECTION_ID = (SELECT ID FROM WEBCONTIFY_COLLECTION WHERE name = 'collection_with_relation') and NAME = 'related_column'));